apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"tasky","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"tasky"}},"template":{"metadata":{"labels":{"app":"tasky"}},"spec":{"containers":[{"env":[{"name":"MONGODB_URI","value":"mongodb://$(MONGODB_USER):$(MONGODB_PASSWORD)@$(MONGODB_HOST):27017/$(MONGODB_DATABASE)?authSource=$(MONGODB_DATABASE)"}],"envFrom":[{"configMapRef":{"name":"mongo-config"}},{"secretRef":{"name":"mongo-creds"}}],"image":"ghcr.io/limalbert96/tasky:latest","name":"tasky","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"securityContext":{"privileged":true,"runAsUser":0}}],"imagePullSecrets":[{"name":"ghcr-secret"}],"serviceAccountName":"tasky-admin"}}}}
  creationTimestamp: "2025-05-13T18:51:28Z"
  generation: 1
  name: tasky
  namespace: default
  resourceVersion: "1747162377990223011"
  uid: 7264293a-bbdd-4692-8fa7-0ffe5f8c69c0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tasky
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tasky
    spec:
      containers:
      - env:
        - name: MONGODB_URI
          value: mongodb://$(MONGODB_USER):$(MONGODB_PASSWORD)@$(MONGODB_HOST):27017/$(MONGODB_DATABASE)?authSource=$(MONGODB_DATABASE)
        envFrom:
        - configMapRef:
            name: mongo-config
        - secretRef:
            name: mongo-creds
        image: ghcr.io/limalbert96/tasky:latest
        imagePullPolicy: Always
        name: tasky
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          privileged: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghcr-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: tasky-admin
      serviceAccountName: tasky-admin
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-13T18:52:57Z"
    lastUpdateTime: "2025-05-13T18:52:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-13T18:51:28Z"
    lastUpdateTime: "2025-05-13T18:52:57Z"
    message: ReplicaSet "tasky-7b84849c96" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
